#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/base?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: base
    password: wkyZjjRYfHmGWdy3

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

mybatis-plus:
  global-config:
    enable-sql-runner: true
